spring.application.name=user
server.port=8082

# CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.orderCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.orderCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderCB.registerHealthIndicator=true

# RETRY
resilience4j.retry.instances.orderCB.maxAttempts=3
resilience4j.retry.instances.orderCB.waitDuration=2s

# RATE LIMITER
resilience4j.ratelimiter.instances.orderCB.limitForPeriod=5
resilience4j.ratelimiter.instances.orderCB.limitRefreshPeriod=10s

# Enable detailed Resilience4j logs
logging.level.io.github.resilience4j=DEBUG
logging.level.com.example.user=DEBUG

